// Generated by LiveScript 1.2.0
(function(){
  var ioClient, url, events, Ref;
  ioClient = require('socket.io-client');
  url = require('url');
  events = require('events');
  Ref = (function(){
    Ref.displayName = 'Ref';
    var prototype = Ref.prototype, constructor = Ref;
    function Ref(uri){
      var ref$;
      ref$ = url.parse(uri), this.host = ref$.host, this.pathname = ref$.pathname;
      ref$ = this.pathname.split('/'), this.tbl = ref$[1], this.id = ref$[2], this.col = ref$[3];
      if (this.col) {
        this.refType = 'column';
        this.id = parseInt(this.id, 10);
      } else if (this.id) {
        this.refType = 'entry';
        this.id = parseInt(this.id, 10);
      } else if (this.tbl) {
        this.refType = 'collection';
      } else {
        this.refType = 'root';
      }
      this.socket = ioClient.connect("http://" + this.host, {
        transports: ['websocket'],
        'force new connection': true,
        'connect timeout': 999999999,
        'reconnect': true,
        'reconnection delay': 500,
        'reopen delay': 500
      });
      this.socket.on('error', function(it){
        console.log('error', it);
        throw it;
      });
    }
    prototype.on = function(event, cb, subscribeCompleteCb){
      var filtered_cb;
      switch (this.refType) {
      case 'collection':
        this.socket.on(this.tbl + ":" + event, cb);
        if (event === 'value') {
          this.socket.emit("GETALL:" + this.tbl, function(it){
            return typeof cb === 'function' ? cb(it) : void 8;
          });
        }
        this.socket.emit("SUBSCRIBE:" + this.tbl + ":" + event, function(){
          return typeof subscribeCompleteCb === 'function' ? subscribeCompleteCb() : void 8;
        });
        break;
      case 'entry':
        switch (event) {
        case 'value':
          this.bare_cbs == null && (this.bare_cbs = {});
          filtered_cb = function(it){
            if (it._id === this.id) {
              return cb(it);
            }
          };
          this.socket.on(this.tbl + ":child_changed", filtered_cb);
          this.bare_cbs[cb] = filtered_cb;
          this.socket.emit("GET:" + this.tbl, {
            _id: this.id
          }, function(it){
            return typeof cb === 'function' ? cb(it) : void 8;
          });
          this.socket.emit("SUBSCRIBE:" + this.tbl + ":child_changed", function(){
            return typeof subscribeCompleteCb === 'function' ? subscribeCompleteCb() : void 8;
          });
          break;
        case 'child_added':
          throw Error('unimplemented');
        case 'child_changed':
          throw Error('unimplemented');
        case 'child_removed':
          throw Error('unimplemented');
        }
        break;
      case 'column':
        switch (event) {
        case 'value':
          this.bare_cbs == null && (this.bare_cbs = {});
          filtered_cb = function(it){
            if (it._id === this.id) {
              return cb(it[this.col]);
            }
          };
          this.socket.on(this.tbl + ":child_changed", filtered_cb);
          this.bare_cbs[cb] = filtered_cb;
          this.socket.emit("GET:" + this.tbl, {
            _id: this.id,
            _column: this.col
          }, function(it){
            return typeof cb === 'function' ? cb(it) : void 8;
          });
          this.socket.emit("SUBSCRIBE:" + this.tbl + ":child_changed", function(){
            return typeof subscribeCompleteCb === 'function' ? subscribeCompleteCb() : void 8;
          });
          break;
        case 'child_added':
          throw Error('unimplemented');
        case 'child_changed':
          throw Error('unimplemented');
        case 'child_removed':
          throw Error('unimplemented');
        }
      }
    };
    prototype.set = function(value, cb){
      var ref$;
      switch (this.refType) {
      case 'collection':
        return this.socket.emit("PUT:" + this.tbl, {
          body: value
        }, function(it){
          return typeof cb === 'function' ? cb(it) : void 8;
        });
      case 'entry':
        return this.socket.emit("PUT:" + this.tbl, {
          body: value,
          u: true
        }, function(it){
          return typeof cb === 'function' ? cb(it) : void 8;
        });
      case 'column':
        return this.socket.emit("PUT:" + this.tbl, {
          _id: this.id,
          body: (ref$ = {}, ref$[this.col + ""] = value, ref$),
          u: true
        }, function(it){
          return typeof cb === 'function' ? cb(it) : void 8;
        });
      }
    };
    prototype.push = function(value, cb){
      switch (this.refType) {
      case 'collection':
        return this.socket.emit("POST:" + this.tbl, {
          body: value
        }, function(it){
          return typeof cb === 'function' ? cb(it) : void 8;
        });
      case 'entry':
        throw Error('unimplemented');
      case 'column':
        throw Error('unimplemented');
      }
    };
    prototype.update = function(value, cb){
      switch (this.refType) {
      case 'collection':
        throw Error('unimplemented');
      case 'entry':
        return this.socket.emit("PUT:" + this.tbl, {
          body: value,
          u: true
        }, function(it){
          return typeof cb === 'function' ? cb(it) : void 8;
        });
      case 'column':
        throw Error('unimplemented');
      }
    };
    prototype.remove = function(cb){
      var ref$;
      switch (this.refType) {
      case 'collection':
        return this.socket.emit("DELETE:" + this.tbl, function(it){
          return typeof cb === 'function' ? cb(it) : void 8;
        });
      case 'entry':
        return this.socket.emit("DELETE:" + this.tbl, {
          _id: this.id
        }, function(it){
          return typeof cb === 'function' ? cb(it) : void 8;
        });
      case 'column':
        return this.socket.emit("PUT:" + this.tbl, {
          _id: this.id,
          body: (ref$ = {}, ref$[this.col + ""] = null, ref$),
          u: true
        }, function(it){
          return typeof cb === 'function' ? cb(it) : void 8;
        });
      }
    };
    prototype.off = function(event, cb){
      var i$, ref$, len$, l, results$ = [];
      switch (this.refType) {
      case 'collection':
        if (cb) {
          for (i$ = 0, len$ = (ref$ = this.socket.listeners(this.tbl + ":" + event)).length; i$ < len$; ++i$) {
            l = ref$[i$];
            if (l === cb) {
              results$.push(this.socket.removeListener(this.tbl + ":" + event, l));
            }
          }
          return results$;
        } else {
          return this.socket.removeAllListeners(this.tbl + ":" + event);
        }
        break;
      case 'entry':
        if (event === 'value') {
          if (cb) {
            if (this.bare_cbs[cb]) {
              return this.socket.removeListener(this.tbl + ":child_changed", this.bare_cbs[cb]);
            }
          } else {
            return this.socket.removeAllListeners(this.tbl + ":child_changed");
          }
        } else {
          throw Error('unimplemented');
        }
        break;
      case 'column':
        if (event === 'value') {
          if (cb) {
            if (this.bare_cbs[cb]) {
              return this.socket.removeListener(this.tbl + ":child_changed", this.bare_cbs[cb]);
            }
          } else {
            return this.socket.removeAllListeners(this.tbl + ":child_changed");
          }
        } else {
          throw Error('unimplemented');
        }
      }
    };
    prototype.once = function(event, cb, subscribeCompleteCb){
      var once_cb, this$ = this;
      switch (this.refType) {
      case 'collection':
        once_cb = function(it){
          cb(it);
          return this$.off(event, once_cb);
        };
        return this.on(event, once_cb, subscribeCompleteCb);
      case 'entry':
        once_cb = function(it){
          if (it._id === this$.id) {
            cb(it);
            return this$.off(event, once_cb);
          }
        };
        return this.on(event, once_cb, subscribeCompleteCb);
      case 'column':
        once_cb = function(it){
          cb(it);
          return this$.off(event, once_cb);
        };
        return this.on(event, once_cb, subscribeCompleteCb);
      }
    };
    prototype.toString = function(){
      return "http://" + this.host + this.pathname;
    };
    prototype.root = function(){
      return "http://" + this.host;
    };
    prototype.name = function(){
      switch (this.refType) {
      case 'collection':
        return this.tbl;
      case 'entry':
        return this.id;
      case 'column':
        return this.col;
      }
    };
    prototype.parent = function(){
      switch (this.refType) {
      case 'collection':
        return this.root();
      case 'entry':
        return this.root() + "/" + this.tbl;
      case 'column':
        return this.root() + "/" + this.tbl + "/" + this.id;
      }
    };
    prototype.child = function(it){
      switch (this.refType) {
      case 'collection':
        return new Ref(this.toString() + "/" + it);
      case 'entry':
        return new Ref(this.toString() + "/" + it);
      case 'column':
        throw Error('unimplemented');
      }
    };
    return Ref;
  }());
  exports.Ref = Ref;
}).call(this);
